
install.packages("sf")
library(sf)
library(raster)
library(dplyr)
install.packages("spData")
library(spData)
install.packages("spDataLarge")
base = get_map(location=c(-120,33,-112.5,38.5), zoom=8, maptype="terrain-background")
require(ggplot2)
require(ggmap)
require(maps)
require(mapproj)
require(mapdata)
require(rgeos)
require(maptools)
require(sp)
require(raster)
require(rgdal)
require(dismo)


range(WS_Fall_2012$Latitude)
range(WS_Fall_2012$Longitude)

base = get_map(location=c(-106.5,32.4,-105.8,32.9), zoom = 12, maptype="terrain-background")
x11()
map1 <- ggmap(base)
  map1 + plot( x = WS_Fall_2012$Longitude , y= WS_Fall_2012$Latitude, cex = 2.5 )
  